name: Deploy to VPS

on:
  push:
    branches:
      - master # Cambia a 'main' si tu rama principal es 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Clona el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # Conéctate al VPS y ejecuta los comandos de despliegue
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 31.220.109.166 # IP de tu servidor VPS
          username: root # Usuario del VPS
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Clave privada configurada en los Secrets
          script: |
            cd /root/sorteos-lisboa # Asegúrate de que esta ruta sea válida
            git pull origin main # Actualiza el repositorio
            npm install # Instala dependencias
            pm2 restart server.js # Reinicia la aplicación con PM2